### ISSUE TITLE
[PE-D][Tester A] Possible to reset to same password

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-F11-3/tp#155] opened 2022-10-29 05:15 UTC
It is possible for the old and new password to be the same

![image.png](https://raw.githubusercontent.com/ALWHgithub/ped/main/files/1230af90-a8a5-4e9f-8c39-b748599355aa.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ALWHgithub/ped#9

**Comment by leecaregene** [comment] 2022-10-29 10:23
Not a bug, won't fix.

**Closed by leecaregene** 2022-10-29 10:23 UTC
Labels: wontfix
